### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by ashishanand7** [samhardyhey/clean-py#1]
Python : 3.6.4
Jupyter 1.0.0
Jupyter-client 5.2.4
Jupyter-core 4.4.0
OS: Windows 10

Runs successfully but doesn't do anything to the file. 
I get "Cleaning file abc.ipynb" and then process completes.
Windows doesn't show file as modified and even on opening there is no change to file.
All unused imports were still there.

![main](https://user-images.githubusercontent.com/20502728/66749197-d52d2c00-eea6-11e9-9fb3-4c374c40ed40.JPG)

**Comment by samhardyhey** [comment]
Hey mate, bit of a hobby project here, unlikely to support windows, but will check out the above behaviour all the same!
